name: kagame_app
description: A new Fluttershy project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+4

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  camera: ^0.10.5+4
  path_provider: ^2.0.11
  image_picker: ^1.1.2
  image: ^4.2.0
  go_router: ^14.2.8 
  flutter_secure_storage: ^9.2.2
  material_tag_editor: ^0.1.2
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.5.2
  syncfusion_flutter_sliders: ^27.2.5
  flutter_launcher_icons: ^0.13.1 
  sse_client: ^0.1.0
  shimmer: ^3.0.0
  flutter_client_sse: ^2.0.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^5.4.4
  universal_io: ^2.2.2
  dropdown_search: ^5.0.6
  url_launcher: ^6.1.5 

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/app_icon.png"  # Path to your logo image

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/stylequiz/
    - lib/assets/countries.txt

  fonts:
    - family:  MyFlutterApp
      fonts:
       - asset: fonts/tshirt_with_wand.ttf
