name: kagame_app
description: A new Fluttershy project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  camera: ^0.10.0+2
  path_provider: ^2.0.11
  image_picker: ^0.8.4+4
  image: ^3.0.2
  go_router: ^7.0.0 
  flutter_secure_storage: ^7.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/